apiVersion: v1
kind: Secret
metadata:
  name: telegram-publisher-secrets
  labels:
    {{- include "truenas-app.labels" . | nindent 4 }}
type: Opaque
data:
  bot-token: {{ .Values.telegram.botToken | b64enc }}
  chat-id: {{ .Values.telegram.chatId | b64enc }}
  truenas-api-key: {{ .Values.truenas.apiKey | b64enc }} 