apiVersion: v2
name: telegram-publisher
description: Приложение для публикации сообщений в Telegram из TrueNAS Scale
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com 